routes/web.php
        Route::GET( "publisher-reserved", "WalletController@reserved" )->name( "wallet.reserved" );
        Route::post( 'send-message', 'MessageController@send_message' )->name( 'send_message' );
    } );
});

// Advertiser
Route::group( [ "middleware" => [ "auth", "redirect_if_not_authenticated" ], "as" => "advertiser.", "prefix" => "advertiser", "namespace" => "Advertiser" ] , function () {
    Route::get('get-user-sites/{id}','AdvertiserController@getUserSites')->name('get.user.sites');
    Route::get('dashboard','AdvertiserController@dashboardOrg')->name('dashboard.org');
    Route::get('sites','AdvertiserController@dashboard')->name('dashboard');
    Route::get('featured-sites','AdvertiserController@feature_dashboard')->name('feature_dashboard');
    Route::get('get-order/{id}','AdvertiserController@getOrder')->name('get.order');
    Route::post('get-order','AdvertiserController@getUserOrder')->name('get.user.order');

    //Activity Log
    Route::get( 'activity-log', 'AdvertiserController@activity_log' )->name('activity.log');

    Route::get('order-status','AdvertiserController@orderStatus')->name('order.status');
    Route::GET( "order-details/{id}","OrderController@order_details" )->name( "order.details" );
    Route::get('order-approve/{id}','AdvertiserController@orderApprove')->name('order.approve');
    Route::get('check-live-link/{id}','AdvertiserController@checkLiveLink')->name('order.check.live.link');
    Route::post('reason','AdvertiserController@reason')->name('reason');
    Route::get('profile','AdvertiserController@profile')->name('profile');
    Route::post('profile','AdvertiserController@profileUpdate')->name('profile.update');
    Route::get('site-filter','AdvertiserController@siteFilter')->name('site.filter');
    Route::get('order-update/{id}','AdvertiserController@orderUpdate')->name('order.update');
    Route::post('order-update','AdvertiserController@orderUpdates')->name('order.updates');

//    Favorite Sites
    Route::get('favorite','AdvertiserController@favorite')->name('favorite');
    Route::get('favorite-sites','AdvertiserController@favorite_sites')->name('sites.favorite');

    // Payments
    Route::GET( "wallet", "WalletController@index" )->name( "wallet.index" );
    Route::GET( "wallet/top-up", "WalletController@top_up_wallet" )->name( "wallet.top-up" );
    Route::PATCH( "wallet/update", "WalletController@update_wallet" )->name( "wallet.update" );
    Route::GET( "wallet/payment/success", "PaymentController@payment_success" )->name( "wallet.payment.success" );
    Route::GET( "wallet/payment/cancelled", "PaymentController@payment_cancelled" )->name( "wallet.payment.cancelled" );

    Route::post('requests-reject', 'AdvertiserController@requestsReject')->name('requests.reject');

    Route::post( 'send-message', 'MessageController@send_message' )->name( 'send_message' );
} );

// Admin
Route::group( [ "middleware" => [ "auth", "redirect_if_not_authenticated" ], "as" => "admin.", "prefix" => "admin", "namespace" => "Admin" ] , function () {

    Route::get('cache-clear','AdminController@cache_clear')->name('cache.clear');


    Route::get('/dashboard','AdminController@index')->name('dashboard');
    Route::get('check-site','AdminController@checkSite')->name('check.site');
//    language
    Route::get('language','AdminController@language')->name('language');
    Route::get('language-status/{id}','AdminController@languageStatus')->name('language.status');

//    Category
    Route::get('add-category','AdminController@addCategory')->name('add.category')->middleware( "can:categories.create" );
    Route::post('store-category','AdminController@storeCategory')->name('store.category')->middleware( "can:categories.create" );
    Route::get('category','AdminController@category')->name('category')->middleware( "can:categories.view" );
    Route::get('del-category/{id}','AdminController@delCategory')->name('delcategory')->middleware( "can:categories.delete" );
    Route::get('edit-category/{id}','AdminController@editCategory')->name('editcategory')->middleware( "can:categories.update" );
    Route::post('update-category/{id}','AdminController@updateCategory')->name('updatecategory')->middleware( "can:categories.update" );

    Route::get('get-user-sites/{id}','AdminController@getUserSites')->name('get.user.sites');

//    Website
    Route::get('site','AdminController@site')->name('site')->middleware( "can:sites.view" );
    Route::get('de-activate-site','AdminController@dsite')->name('dsite')->middleware( "can:sites.view" );
    Route::get('pending-activate-site','AdminController@psite')->name('psite')->middleware( "can:sites.view" );
    Route::get('change-status/{id}','AdminController@changeStatus')->name('change.status')->middleware( "can:sites.view" );
    Route::get('change-pending-status/{id}','AdminController@changePendingStatus')->name('change.pending.status')->middleware( "can:sites.view" );
    Route::get('add-site','AdminController@addSite')->name('add.Site')->middleware( "can:sites.create" );
    Route::post('store-site','AdminController@storeSite')->name('store.Site')->middleware( "can:sites.create" );
    Route::get('del-site/{id}','AdminController@delSite')->name('del.Site')->middleware( "can:sites.delete" );
    Route::get('edit-site/{id}','AdminController@editSite')->name('edit.Sites')->middleware( "can:sites.update" );
    Route::post('update-site/{id}','AdminController@updateSite')->name('update.Site')->middleware( "can:sites.update" );
    Route::get('reject-site/{id}','AdminController@rejectSite')->name('reject.Site')->middleware( "can:sites.delete" );
    Route::get('rejected-site','AdminController@rejectedSite')->name('rejected.Site')->middleware( "can:sites.delete" );

    // Roles
    Route::GET( "roles", "RoleController@index" )->name( "roles.index" )->middleware( "can:roles.view" );
    Route::GET( "roles/create", "RoleController@create" )->name( "roles.create" )->middleware( "can:roles.create" );
    Route::POST( "roles", "RoleController@store" )->name( "roles.store" )->middleware( "can:roles.create" );
    Route::GET( "roles/{role}/edit", "RoleController@edit" )->name( "roles.edit" )->middleware( "can:roles.update" );
    Route::PATCH( "roles/{role}", "RoleController@update" )->name( "roles.update" )->middleware( "can:roles.update" );
    Route::DELETE( "roles/{role}", "RoleController@delete" )->name( "roles.destroy" )->middleware( "can:roles.delete" );

    // Users
    Route::GET( "users", "UserController@index" )->name( "users.index" )->middleware( "can:users.view" );
    Route::GET( "users/create", "UserController@create" )->name( "users.create" )->middleware( "can:users.create" );
    Route::POST( "users", "UserController@store" )->name( "users.store" )->middleware( "can:users.create" );
    Route::GET( "users/{user}/edit", "UserController@edit" )->name( "users.edit" )->middleware( "can:users.update" );
    Route::PATCH( "users/{user}", "UserController@update" )->name( "users.update" )->middleware( "can:users.update" );
    Route::DELETE( "users/{user}", "UserController@delete" )->name( "users.destroy" )->middleware( "can:users.delete" );
    Route::GET( "user-status/{id}", "UserController@status" )->name( "user.status" )->middleware( "can:users.view" );

    // Staff
    Route::GET( "staff", "StaffController@index" )->name( "staff.index" )->middleware( "can:staff.view" );
    Route::GET( "staff/create", "StaffController@create" )->name( "staff.create" )->middleware( "can:staff.create" );
    Route::POST( "staff", "StaffController@store" )->name( "staff.store" )->middleware( "can:staff.create" );
    Route::GET( "staff/{id}/edit", "StaffController@edit" )->name( "staff.edit" )->middleware( "can:staff.update" );
    Route::PATCH( "staff/{id}", "StaffController@update" )->name( "staff.update" )->middleware( "can:staff.update" );
    Route::DELETE( "staff/{id}", "StaffController@delete" )->name( "staff.destroy" )->middleware( "can:staff.delete" );

    Route::GET( "task", "TaskController@index" )->name( "task.index" )->middleware( "can:task.view" );
    Route::GET( "task-detail/{id}", "TaskController@detail" )->name( "task.detail" )->middleware( "can:task.view" );
    Route::GET( "user-task-detail/{id}", "TaskController@userTaskDetail" )->name( "user.task.detail" )->middleware( "can:task.view" );
    Route::GET( "task-filter", "TaskController@filter" )->name( "task.filter" )->middleware( "can:task.view" );

    Route::get('profile','TaskController@profile')->name('profile');
    Route::post('profile','TaskController@profileUpdate')->name('profile.update');

    Route::post('profile','TaskController@profileUpdate')->name('profile.update');
    Route::get('site-filter','TaskController@siteFilter')->name('site.filter');

    // Wallet Top Up History
    Route::GET( "wallet/top-up/history", "WalletTopUpController@index" )->name( "wallet.top_up.history" );

    // Withdraw Request
    Route::GET( "wallet/withdraw/requests", "WalletController@withdraw_requests" )->name( "wallet.withdraw.request" ) ;
    Route::GET( "wallet/withdraw/requests-status/{id}", "WalletController@withdraw_requests_status" )->name( "wallet.withdraw.request.status" ) ;

    // Transaction History
    Route::GET( "wallet/transaction/history", "WalletController@index" )->name( "wallet.transaction.history" );
    Route::GET( "wallet/transactions", "WalletController@create_transaction" )->name( "wallet.transaction.create" );
    Route::POST( "wallet/transactions", "WalletController@store_transaction" )->name( "wallet.transaction.store" );

    // Blog
    Route::GET( "blog", "BlogController@blog" )->name( "blog" );
    Route::GET( "blog-create", "BlogController@create" )->name( "blog.create" );
    Route::POST( "blog-store", "BlogController@store" )->name( "blog.store" );
    Route::GET( "blog-delete/{id}", "BlogController@delete" )->name( "blog.delete" );
    Route::GET( "blog-edit/{id}", "BlogController@edit" )->name( "blog.edit" );

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Role extends Model
{
    use softDeletes;

    public function modules ()
    {
        return $this->belongsToMany( "App\Module", "module_role", "role_id", "module_id" )->withPivot( "can_create", "can_view", "can_update", "can_delete" );
    }

    public function users ()
    {
        return $this->hasMany( User::class, "id", "role_id" );
    }

}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Role;
use App\Module;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;

class RoleController extends Controller
{
    public function index ()
    {
        $roles = Role::where( "id", ">", 3 )
            ->select( "id", "role", "created_at" )
            ->latest()
            ->get();

        return view( "admin.roles.index", compact( "roles" ) );
    }

    public function create ()
    {
        $modules = Module::all( "id", "module" );

        return view( "admin.roles.create", compact( "modules" ) );
    }

    public function store ( Request $request )
    {
        $request->validate( [
            "role" => "required|max:255|unique:roles,role"
        ] );

        $module_error = true;

        foreach ( $request->module_ids as $module_id ) {
            $create = $request->get( "module_" . $module_id . "_create" );
            $view = $request->get( "module_" . $module_id . "_view" );
            $update = $request->get( "module_" . $module_id . "_update" );
            $delete = $request->get( "module_" . $module_id . "_delete" );

            if ( isset( $create ) || isset( $view ) || isset( $update ) || isset( $delete ) ) {
                $module_error = false;
            }
        }

        if ( $module_error ) {
            return redirect()->back()->with( "error", "Please check at least one module." )->withInput();
        }

        DB::beginTransaction();

        try {
            $role = new Role();
            $role->role = $request->role;
            $role->save();
    
            foreach ( $request->module_ids as $module_id ) {
                $create = $request->get( "module_" . $module_id . "_create" );
                $view = $request->get( "module_" . $module_id . "_view" );
                $update = $request->get( "module_" . $module_id . "_update" );
                $delete = $request->get( "module_" . $module_id . "_delete" );
    
                if ( isset( $create ) || isset( $view ) || isset( $update ) || isset( $delete ) ) {
                    $role->modules()->attach( [ $module_id ], [ "can_create" => isset( $create ) ? 1 : 0, "can_view" => isset( $view ) ? 1 : 0, "can_update" => isset( $update ) ? 1 : 0, "can_delete" => isset( $delete ) ? 1 : 0 ] );
                }
            }

            DB::commit();

        } catch ( \Exception $e ) {
            DB::rollBack();

            return $e->getMessage();
        }

        return redirect()->route( "admin.roles.index" )->with( "success", "Role has been created." );
    }

    public function edit ( Request $request, $id )
    {
        if ( Role::where( "id", $id )->doesntExist() ) {
            return redirect()->route( "admin.roles.index" );
        }

        $role = Role::where( "id", $id )
            ->select( "id", "role" )
            ->with( "modules:id,module" )
            ->latest()
            ->first();

        $modules = Module::all( "id", "module" );

        return view( "admin.roles.edit", compact( "role", "modules" ) );
    }

    public function update ( Request $request, $id )
    {
        $request->validate( [
            "role" => "required|max:255|unique:roles,role," . $id
        ] );

        $module_error = true;

        foreach ( $request->module_ids as $module_id ) {
            $create = $request->get( "module_" . $module_id . "_create" );
            $view = $request->get( "module_" . $module_id . "_view" );
            $update = $request->get( "module_" . $module_id . "_update" );
            $delete = $request->get( "module_" . $module_id . "_delete" );

            if ( isset( $create ) || isset( $view ) || isset( $update ) || isset( $delete ) ) {
                $module_error = false;
            }
        }

        if ( $module_error ) {
            return redirect()->back()->with( "error", "Please check at least one module." )->withInput();
        }

        if ( Role::where( "id", $id )->exists() ) {
            $role = Role::findOrFail( $id );

            DB::beginTransaction();

            try {
                $role->role = $request->role;
                $role->save();

                $role->modules()->detach();

                foreach ( $request->module_ids as $module_id ) {
                    $create = $request->get( "module_" . $module_id . "_create" );
                    $view = $request->get( "module_" . $module_id . "_view" );
                    $update = $request->get( "module_" . $module_id . "_update" );
                    $delete = $request->get( "module_" . $module_id . "_delete" );

                    if ( isset( $create ) || isset( $view ) || isset( $update ) || isset( $delete ) ) {
                        $role->modules()->attach( [ $module_id ], [ "can_create" => isset( $create ) ? 1 : 0, "can_view" => isset( $view ) ? 1 : 0, "can_update" => isset( $update ) ? 1 : 0, "can_delete" => isset( $delete ) ? 1 : 0 ] );
                    }
                }

                DB::commit();

            } catch ( \Exception $e ) {
                DB::rollBack();

                return $e->getMessage();
            }
        }

        return redirect()->route( "admin.roles.index" )->with( "success", "Role has been updated." );
    }

    public function delete ( Request $request, $id )
    {
        if ( Role::where( "id", $id )->exists() ) {
            Role::where( "id", $id )->delete();
        }

    	return redirect()->route( "admin.roles.index" )->with( "success", "Role has been deleted." );
    }
}

resources/views/admin/roles/create.blade.php
@extends('layout.admin.app')
    @section('title')
        Add New Role
    @endsection

    @section( "css" )
        <link rel="stylesheet" href="{{ asset( 'css/roles/create.css' ) }}">
    @endsection

    @section('content')
        <div class="main-content {{ config('app_logo.BLOCKCOLOR') }}">
            <div class="page-content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-12">
                            <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                                <h4 class="mb-sm-0 font-size-18 {{ config('app_logo.TEXTCOLOR') }}">Add New Role</h4>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-12">
                            @include( "error.message" )

                            <div class="card {{ config('app_logo.BLOCKCOLOR') }} shadow-lg">
                                <div class="card-body">
                                    <form action="{{ route('admin.roles.store') }}" method="POST" id="roles_form">
                                        @csrf

                                        <div class="col-6 mb-4">
                                            <div class="form-group">
                                                <label for="role">Role</label>

                                                <input type="text" id="role" name="role" placeholder="Role" class="form-control @error( 'role' ) is-invalid @enderror input_field" value="{{ old( 'role' ) }}">

                                                @error( 'role' )
                                                    <small class="text-danger form-text">{{ $message }}</small>
                                                @enderror

                                                <small class="text-danger form-text input_field_validation_status" id="role_validation_status"></small>
                                            </div>
                                        </div>

                                        <div class="col-sm-9">
                                            <div class="form-group" id="modules_container">
                                                <div class="row mt-3 mb-2">
                                                    <div class="col-2">
                                                        <label>Modules</label>
                                                    </div>

                                                    <div class="col-2 text-center">
                                                        <label>Create</label>
                                                    </div>

                                                    <div class="col-2 text-center">
                                                        <label>View</label>
                                                    </div>

                                                    <div class="col-2 text-center">
                                                        <label>Update</label>
                                                    </div>

                                                    <div class="col-2 text-center">
                                                        <label>Delete</label>
                                                    </div>
                                                </div>

                                                @foreach ( $modules as $module )
                                                    <input type="hidden" name="module_ids[]" value="{{ $module->id }}">

                                                    <div class="row align-items-center mb-2">
                                                        <div class="col-2">
                                                            {{ $module->module }}
                                                        </div>

                                                        <div class="col-2 text-center">
                                                            <input type="checkbox" @if( old( "module_" . $module->id . "_create" ) && old( "module_" . $module->id . "_create" ) == "on" ) {{ "checked" }} @endif name="module_{{ $module->id }}_create" id="module_{{ $module->id }}_create">
                                                        </div>

                                                        <div class="col-2 text-center">
                                                            <input type="checkbox" @if( old( "module_" . $module->id . "_view" ) && old( "module_" . $module->id . "_view" ) == "on" ) {{ "checked" }} @endif name="module_{{ $module->id }}_view" id="module_{{ $module->id }}_view">
                                                        </div>

                                                        <div class="col-2 text-center">
                                                            <input type="checkbox" @if( old( "module_" . $module->id . "_update" ) && old( "module_" . $module->id . "_update" ) == "on" ) {{ "checked" }} @endif name="module_{{ $module->id }}_update" id="module_{{ $module->id }}_update">
                                                        </div>

                                                        <div class="col-2 text-center">
                                                            <input type="checkbox" @if( old( "module_" . $module->id . "_delete" ) && old( "module_" . $module->id . "_delete" ) == "on" ) {{ "checked" }} @endif name="module_{{ $module->id }}_delete" id="module_{{ $module->id }}_delete">
                                                        </div>
                                                    </div>
                                                @endforeach
                                            </div>

                                            <div class="col-sm-10 mt-3" id="role_form_footer">
                                                <div class="d-flex align-items-center justify-content-between">
                                                    <button type="submit" id="submitBtn" class="btn btn-primary px-4">Submit</button>

                                                    <div class="alert alert-danger m-0" id="invalid_role_error_block">
                                                        Please check at least one module.
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <footer class="footer">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <script>document.write(new Date().getFullYear())</script> © Publication Media.
                        </div>
                        <div class="col-sm-6">
                            <div class="text-sm-end d-none d-sm-block">
{{--                                Design & Develop by Themesbrand--}}
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    @endsection

    @push('scripts')
        <script src="{{ asset( 'js/roles/create.js' ) }}">
    @endpush

resources/views/admin/roles/index.blade.php
@extends('layout.admin.app')
@section('title')
    Roles
@endsection
@section('content')
<div class="main-content {{ config('app_logo.BLOCKCOLOR') }}">

    <div class="page-content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-12">
                    <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                        <h4 class="mb-sm-0 font-size-18 {{ config('app_logo.TEXTCOLOR') }}">Roles</h4>

                        @can ( "roles.create" )
                            <a href="{{ route('admin.roles.create') }}" class="btn btn-primary ">Add New Role</a>
                        @endcan
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    @include('error.message')

                    <div class="card {{ config('app_logo.BLOCKCOLOR') }} shadow-lg">
                        <div class="card-body">
                            <h4 class="card-title mb-4 {{ config('app_logo.TEXTCOLOR') }}">Roles</h4>

                            <div class="table-responsive">
                                <table class="table align-middle table-nowrap mb-0">
                                    <thead>
                                        <tr>
                                            <th class="align-middle text-black">SR.</th>
                                            <th class="align-middle text-black">Role</th>
                                            <th class="align-middle text-black">Created At</th>
                                            <th class="align-middle text-black">Action</th>
                                        </tr>
                                    </thead>

                                    <tbody>
                                        @foreach( $roles as $index => $role )
                                            <tr>
                                                <td class="text-black">
                                                    {{ ++$index }}
                                                </td>

                                                <td class="text-black">
                                                    {{ isset( $role->role ) ? $role->role : "" }}
                                                </td>

                                                <td class="text-black">
                                                    {{ $role->created_at->diffForHumans() }}
                                                </td>

                                                <td class="text-black">
                                                    @can ( "roles.edit" )
                                                        <a href="{{ route( 'admin.roles.edit',$role->id ) }}" type="button" class="btn btn-primary waves-effect waves-light">
                                                            Edit
                                                        </a>
                                                    @endcan

                                                    @can ( "roles.delete" )
                                                        <form action="{{ route( 'admin.roles.destroy', [ 'role' => $role->id ] ) }}" method="POST" class="d-inline">
                                                            @csrf
                                                            @method( "DELETE" )

                                                            <button type="submit" class="btn btn-danger waves-effect waves-light" onclick="return confirm('Are you sure?')">
                                                                Delete
                                                            </button>
                                                        </form>
                                                    @endcan
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <footer class="footer">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6">
                    <script>document.write(new Date().getFullYear())</script> © Publication Media.
                </div>
                <div class="col-sm-6">
                    <div class="text-sm-end d-none d-sm-block">
{{--                        Design & Develop by Themesbrand--}}
                    </div>
                </div>
            </div>
        </div>
    </footer>
</div>
@endsection