routes/web.php
//Route::get('send-mail',function(){
//    $to = 'usmantahir.mashkraft@gmail.com';
//    $subject = "Email Subject";
//
//    $message = 'Dear ' . 'star' . ',<br>';
//    $message .= "We welcome you to be part of family<br><br>";
//    $message .= "Regards,<br>";
//
//// Always set content-type when sending HTML email
//    $headers = "MIME-Version: 1.0" . "\r\n";
//    $headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";
//
//// More headers
//    $headers .= 'From: <hello@dcsfashionstudio.com>' . "\r\n";
//
//    mail($to, $subject, $message, $headers);
//});


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/a',function (){
//
//    $input = array(1,2,2,2,2,8,9);
//
//    $maxElement = 0;
//
//    for($i=0;$i<count($input);$i++) {
//        $count = 0;
//        for ($j = 0; $j < count($input); $j++) {
//            if ($input[$i] == $input[$j]) {
//                $count++;
//            }
//        }
//        if($count>$maxElement){
//            $maxElement = $count;
//            $a = $input[$i];
//        }
//    }
//
//    return  $a.' -> '.$maxElement;

//    $array = ['2,3,1,4,6,5,3'];

//    for($x=0;$x< count($a);$x++)
//    {
//        $min = $x;
//        for($y=$x+1;$y< count($a);$y++)
//        {
//            if($a[$y] < $a[$min] )
//            {
//                $temp = $a[$min];
//                $a[$min] = $a[$y];
//                $a[$y] = $temp;
//            }
//        }
//    }
//    return $a;

//});

Route::get( 'check', function (){
//    $url = 'https://thetrustblog.com/innovative-water-management-techniques-for-farming-in-arid-regions/';
//    $headers = @get_headers( $url );
//
//    // Check if $headers is an array and the first element contains "200 OK"
//    dd( is_array($headers) && strpos($headers[0], '200 OK') !== false );

    $searchUrl = "https://www.google.com/search?q=site:" . urlencode('https://thetrustblog.com/innovative-water-management-techniques-for-farming-in-arid-regions/');
    $searchHtml = file_get_contents( $searchUrl );

    // Check if the post URL appears in the search results
    dd( strpos($searchHtml, 'https://thetrustblog.com/innovative-water-management-techniques-for-farming-in-arid-regions/') !== false );

} );

Route::get( 'verified', 'Admin\AdminController@verified')->name( 'verified' );
Route::post( 'verified-post', 'Admin\AdminController@verified_post')->name( 'verified_post' );

Route::get('return-reserved-payment','CronController@return_reserved_payment')->name('return_reserved_payment');

ROUTE::GET( "/", "IndexController@index" )->name( '/' );
ROUTE::GET( "contact-us", "IndexController@contact" )->name( 'contact' );
ROUTE::GET( "privacy-policy", "IndexController@privacy_policy" )->name( 'privacy_policy' );
ROUTE::GET( "term-condition", "IndexController@term_condition" )->name( 'term_condition' );
ROUTE::GET( "blog/{slug}", "IndexController@blog_detail" )->name( 'blog_detail' );
ROUTE::GET( "blog", "IndexController@blog" )->name( 'blog' );
ROUTE::GET( "go_to_dashboard", "IndexController@go_to_dashboard" )->name( 'go_to_dashboard' );

Auth::routes();

// Publisher
Route::group( [ "middleware" => [ "auth", "redirect_if_not_authenticated" ], "as" => "publisher." ] , function () {
	// Dashboard
    Route::get('/dashboard','HomeController@dashboard')->name('dashboard');

    Route::group( [ "prefix" => "publisher" ], function () {

		// Sites
	    Route::get('list-site','HomeController@listSite')->name('list.site');
	    Route::get('disable-list-site','HomeController@dSite')->name('dsite');
	    Route::get('pending-list-site','HomeController@pSite')->name('psite');
	    Route::get('delete-site/{id}','HomeController@deleteSite')->name('del.site');
	    Route::get('add-new-site','HomeController@addSite')->name('add.site');
	    Route::post('post-site','HomeController@postSite')->name('post.site');
	    Route::get('edit-site/{id}','HomeController@editSite')->name('edit.site');
	    Route::post('update-site/{id}','HomeController@updateSite')->name('update.site');
        Route::get('site-members/{id}','HomeController@siteMember')->name('site.member');
        Route::get('download-file','HomeController@downloadFile')->name('download.file');
        Route::get('verify-owner-ship/{id}','HomeController@verifyOwnerShip')->name('verify.owner.ship');
        Route::get( 'publisher-activity-log', 'HomeController@activity_log' )->name('publisher.activity.log');
        Route::get('rejected-list-site','HomeController@rejectedSite')->name('rejected.site');

	    //Task
        Route::get('task','HomeController@task')->name('task');
        Route::get('show-task-detail/{id}','HomeController@showTaskDetail')->name('show.task.detail');
        Route::get('task-accept/{id}','HomeController@getTaskDetail')->name('task.accept');
        Route::get('task-reject/{id}','HomeController@getTaskReject')->name('task.reject');
        Route::post('request-approve','HomeController@requestApprove')->name('request.approve');
        Route::post('request-reject','HomeController@requestReject')->name('request.reject');

        Route::get('profile','HomeController@profile')->name('profile');
        Route::post('profile','HomeController@profileUpdate')->name('profile.update');

        // Wallet
        Route::GET( "wallet", "WalletController@index" )->name( "wallet.index" );
        Route::GET( "wallet/withdraw", "WalletController@withdraw" )->name( "wallet.withdraw" );
        Route::POST( "wallet/withdraw/request", "WalletController@withdraw_request" )->name( "wallet.withdraw.request" );

        Route::GET( "publisher-reserved", "WalletController@reserved" )->name( "wallet.reserved" );
        Route::post( 'send-message', 'MessageController@send_message' )->name( 'send_message' );
    } );
});

// Advertiser
Route::group( [ "middleware" => [ "auth", "redirect_if_not_authenticated" ], "as" => "advertiser.", "prefix" => "advertiser", "namespace" => "Advertiser" ] , function () {
    Route::get('get-user-sites/{id}','AdvertiserController@getUserSites')->name('get.user.sites');
    Route::get('dashboard','AdvertiserController@dashboardOrg')->name('dashboard.org');
    Route::get('sites','AdvertiserController@dashboard')->name('dashboard');
    Route::get('featured-sites','AdvertiserController@feature_dashboard')->name('feature_dashboard');
    Route::get('get-order/{id}','AdvertiserController@getOrder')->name('get.order');
    Route::post('get-order','AdvertiserController@getUserOrder')->name('get.user.order');

    //Activity Log
    Route::get( 'activity-log', 'AdvertiserController@activity_log' )->name('activity.log');

    Route::get('order-status','AdvertiserController@orderStatus')->name('order.status');
    Route::GET( "order-details/{id}","OrderController@order_details" )->name( "order.details" );
    Route::get('order-approve/{id}','AdvertiserController@orderApprove')->name('order.approve');
    Route::get('check-live-link/{id}','AdvertiserController@checkLiveLink')->name('order.check.live.link');
    Route::post('reason','AdvertiserController@reason')->name('reason');
    Route::get('profile','AdvertiserController@profile')->name('profile');
    Route::post('profile','AdvertiserController@profileUpdate')->name('profile.update');
    Route::get('site-filter','AdvertiserController@siteFilter')->name('site.filter');
    Route::get('order-update/{id}','AdvertiserController@orderUpdate')->name('order.update');
    Route::post('order-update','AdvertiserController@orderUpdates')->name('order.updates');

//    Favorite Sites
    Route::get('favorite','AdvertiserController@favorite')->name('favorite');
    Route::get('favorite-sites','AdvertiserController@favorite_sites')->name('sites.favorite');

    // Payments
    Route::GET( "wallet", "WalletController@index" )->name( "wallet.index" );
    Route::GET( "wallet/top-up", "WalletController@top_up_wallet" )->name( "wallet.top-up" );
    Route::PATCH( "wallet/update", "WalletController@update_wallet" )->name( "wallet.update" );
    Route::GET( "wallet/payment/success", "PaymentController@payment_success" )->name( "wallet.payment.success" );
    Route::GET( "wallet/payment/cancelled", "PaymentController@payment_cancelled" )->name( "wallet.payment.cancelled" );

    Route::post('requests-reject', 'AdvertiserController@requestsReject')->name('requests.reject');

    Route::post( 'send-message', 'MessageController@send_message' )->name( 'send_message' );
} );

// Admin
Route::group( [ "middleware" => [ "auth", "redirect_if_not_authenticated" ], "as" => "admin.", "prefix" => "admin", "namespace" => "Admin" ] , function () {

    Route::get('cache-clear','AdminController@cache_clear')->name('cache.clear');


    Route::get('/dashboard','AdminController@index')->name('dashboard');
    Route::get('check-site','AdminController@checkSite')->name('check.site');
//    language
    Route::get('language','AdminController@language')->name('language');
    Route::get('language-status/{id}','AdminController@languageStatus')->name('language.status');

//    Category
    Route::get('add-category','AdminController@addCategory')->name('add.category')->middleware( "can:categories.create" );
    Route::post('store-category','AdminController@storeCategory')->name('store.category')->middleware( "can:categories.create" );
    Route::get('category','AdminController@category')->name('category')->middleware( "can:categories.view" );
    Route::get('del-category/{id}','AdminController@delCategory')->name('delcategory')->middleware( "can:categories.delete" );
    Route::get('edit-category/{id}','AdminController@editCategory')->name('editcategory')->middleware( "can:categories.update" );

resources/views/dashboard/dashboard.blade.php
@extends('layout.app')
@section('title')
    Dashboard
@endsection
@push('css')
    <style type="text/css">
        .highcharts-button {
            visibility: hidden;
        }

        .userinfo_box {
            display: -webkit-box;
            display: -ms-flexbox;
            display: flex;
            -webkit-box-align: center;
            -ms-flex-align: center;
            align-items: center;
        }

        .userinfo_box figure,
        .userinfo_box figcaption {
            margin: 0;
        }

        .userinfo_box figure {
            min-width: 40px;
            width: 40px;
            height: 40px;
            border-radius: 40px;
            overflow: hidden;
            margin-right: 10px;
        }

        .userinfo_box figure img {
            width: 40px;
            height: 40px;
            border-radius: 40px;
            object-fit: cover;
        }

        .userinfo_box figcaption {
            font-size: 16px;
            color: #a05ca9;
            font-weight: 600;
            line-height: 1.4;
        }

        .userinfo_box figcaption small {
            color: #999;
            text-transform: capitalize;
            display: block;
        }

        .fw-500 {
            font-weight: 500;
        }

        .announcements_wrap {
            height: 380px;
            overflow: auto;
            overflow-x: hidden;
            padding-right: 1rem;
        }

        .ellPara {
            white-space: nowrap;
            text-overflow: ellipsis;
            overflow: hidden;
        }

        .text-purple {
            color: #a05ca9;
        }

        .fs-36 {
            font-size: 36px !important;
        }

        .width-100p {
            width: 100%;
        }

        .announc_figwidth {
            width: calc(100% - 40px);
        }
    </style>
@endpush
@section('content')
<div class="main-content {{ config('app_logo.BLOCKCOLOR') }}">

    <div class="page-content">
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                        <h4 class="mb-sm-0 font-size-18 {{ config('app_logo.BLOCKCOLOR') }}">Dashboard</h4>
                    </div>
                </div>
            </div>
            <!-- end page title -->
            <div class="row">
                <div class="col-xl-12">
                    <div class="row">
                        <div class="col-md-4">
                            <a href="{{ route('publisher.list.site') }}">
                            <div class="card mini-stats-wid {{ config('app_logo.BLOCKCOLOR') }} shadow-lg">
                                <div class="card-body">
                                    <div class="d-flex">
                                        <div class="flex-grow-1">
                                            <p class="text-muted fw-medium {{ config('app_logo.BLOCKCOLOR') }}">Total Sites</p>
                                            <h4 class="mb-0 {{ config('app_logo.BLOCKCOLOR') }}">
                                                {{ \App\Site::where('user_id',Auth::id())->count() }}
                                            </h4>
                                        </div>

                                        <div class="flex-shrink-0 align-self-center">
                                            <div class="mini-stat-icon avatar-sm rounded-circle bg-primary align-self-center">
                                                <span class="avatar-title">
                                                    <i class="bx bx-link-alt font-size-24"></i>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            </a>
                        </div>
                        <div class="col-md-4">
                            <a href="{{ route('publisher.task') }}">
                            <div class="card mini-stats-wid {{ config('app_logo.BLOCKCOLOR') }} shadow-lg">
                                <div class="card-body">
                                    <div class="d-flex">
                                        <div class="flex-grow-1">
                                            <p class="text-muted fw-medium {{ config('app_logo.BLOCKCOLOR') }}">Pending Orders</p>
                                            <h4 class="mb-0 {{ config('app_logo.BLOCKCOLOR') }}">
                                                {{ \App\Order::where('publisher_id',Auth::id())->where('status',0)->count() }}
                                            </h4>
                                        </div>

                                        <div class="flex-shrink-0 align-self-center">
                                            <div class="avatar-sm rounded-circle bg-primary align-self-center mini-stat-icon">
                                                <span class="avatar-title rounded-circle bg-primary">
                                                    <i class="bx bxs-bell-ring font-size-24"></i>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            </a>
                        </div>
                        <div class="col-md-4">
                            <a href="{{ route('publisher.task') }}">
                            <div class="card mini-stats-wid {{ config('app_logo.BLOCKCOLOR') }} shadow-lg">
                                <div class="card-body">
                                    <div class="d-flex">
                                        <div class="flex-grow-1">
                                            <p class="text-muted fw-medium {{ config('app_logo.BLOCKCOLOR') }}">Completed Orders</p>
                                            <h4 class="mb-0 {{ config('app_logo.BLOCKCOLOR') }}">{{ \App\Order::where('publisher_id',Auth::id())->where('status',4)->count() }}</h4>
                                        </div>

                                        <div class="flex-shrink-0 align-self-center">
                                            <div class="avatar-sm rounded-circle bg-primary align-self-center mini-stat-icon">
                                                <span class="avatar-title rounded-circle bg-primary">
                                                    <i class="bx bx-like font-size-24"></i>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            </a>
                        </div>
                    </div>
                    <!-- end row -->
                </div>
            </div>
            <!-- end row -->


            <div class="row">
                <div class="col-lg-12">
                    <div class="card {{ config('app_logo.BLOCKCOLOR') }} shadow-lg">
                        <div class="card-body">
                            <h3 class="card-title mb-4 {{ config('app_logo.BLOCKCOLOR') }}">Pending Orders</h3>
                            <div id="user_detailChart" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
                            <!-- end table-responsive -->
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <div class="card {{ config('app_logo.BLOCKCOLOR') }} shadow-lg">
                        <div class="card-body">
                            <h3 class="card-title mb-4 {{ config('app_logo.BLOCKCOLOR') }}">Completed Orders</h3>
                            <div id="completed_orders" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
                            <!-- end table-responsive -->
                        </div>
                    </div>
                </div>
            </div>
            <!-- end row -->
        </div>
        <!-- container-fluid -->
    </div>
    <!-- End Page-content -->

    <footer class="footer">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6">
                    <script>document.write(new Date().getFullYear())</script> © Publication Media.
                </div>
                <div class="col-sm-6">
                    <div class="text-sm-end d-none d-sm-block">
{{--                        Design & Develop by Themesbrand--}}
                    </div>
                </div>
            </div>
        </div>
    </footer>
</div>
@endsection
@push('scripts')
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/highcharts-more.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script>
        Highcharts.setOptions({
            lang: {
                shortMonths: [
                    'jan', 'feb',
                    'mar', 'apr',
                    'may', 'june',
                    'july', 'aug',
                    'sep', 'oct',
                    'nov', 'dec'
                ],
                months: [
                    'january', 'february',
                    'march', 'april',
                    'may', 'june',
                    'july', 'august',
                    'september', 'october',
                    'november', 'december',
                ],
                weekdays: [
                    'mon', 'tue',
                    'wed', 'thur',
                    'fri', 'sat',
                    'sun',
                ]
            }
        });

        var currentTime = new Date();
        var day = currentTime.getDate();
        var month = currentTime.getMonth() - 1;
        var year = currentTime.getFullYear();
        var pintstartDate = Date.UTC(year, month, day);

        var dates = [];
        var total = [];

        $.each(<?php echo json_encode($pendings); ?>, function (index, value) {
            total.push(parseInt(value.total))
            dates.push(value.created_date);
        });

        Highcharts.chart('user_detailChart', {
            global: {
                // useUTC: false
            },
            chart: {
                zoomType: 'x',
                backgroundColor: '#EFF2F7',
            },

            title: {
                text: 'Pending Orders'
            },

            xAxis: {
                // type: 'datetime'
                categories: dates
            },

            yAxis: {
                allowDecimals: false,
                title: {
                    text: null
                }
            },

            tooltip: {
                crosshairs: true,
                shared: true

            },

            credits: {
                enabled: false
            },

            legend: {
                enabled: false
            },

            series: [{
                name: 'Pending Orders',
                data: total,
            }]
        });

        var com_dates = [];
        var com_total = [];

        $.each(<?php echo json_encode($completes); ?>, function (index, value) {
            com_total.push(parseInt(value.total))
            com_dates.push(value.created_date);
            console.log(com_total);
            console.log(com_dates);
        });

        Highcharts.chart('completed_orders', {
            global: {
                // useUTC: false
            },
            chart: {
                zoomType: 'x',
                backgroundColor: '#EFF2F7',
            },

            title: {
                text: 'Completed Orders'
            },

            xAxis: {
                // type: 'datetime'
                categories: com_dates
            },

            yAxis: {
                allowDecimals: false,
                title: {
                    text: null
                }
            },

            tooltip: {
                crosshairs: true,
                shared: true

            },

            credits: {
                enabled: false
            },

            legend: {
                enabled: false
            },

            series: [{
                name: 'Completed Orders',
                data: com_total,
            }]
        });
    </script>
@endpush