routes/web.php
        Route::GET( "publisher-reserved", "WalletController@reserved" )->name( "wallet.reserved" );
        Route::post( 'send-message', 'MessageController@send_message' )->name( 'send_message' );
    } );
});

// Advertiser
Route::group( [ "middleware" => [ "auth", "redirect_if_not_authenticated" ], "as" => "advertiser.", "prefix" => "advertiser", "namespace" => "Advertiser" ] , function () {
    Route::get('get-user-sites/{id}','AdvertiserController@getUserSites')->name('get.user.sites');
    Route::get('dashboard','AdvertiserController@dashboardOrg')->name('dashboard.org');
    Route::get('sites','AdvertiserController@dashboard')->name('dashboard');
    Route::get('featured-sites','AdvertiserController@feature_dashboard')->name('feature_dashboard');
    Route::get('get-order/{id}','AdvertiserController@getOrder')->name('get.order');
    Route::post('get-order','AdvertiserController@getUserOrder')->name('get.user.order');

    //Activity Log
    Route::get( 'activity-log', 'AdvertiserController@activity_log' )->name('activity.log');

    Route::get('order-status','AdvertiserController@orderStatus')->name('order.status');
    Route::GET( "order-details/{id}","OrderController@order_details" )->name( "order.details" );
    Route::get('order-approve/{id}','AdvertiserController@orderApprove')->name('order.approve');
    Route::get('check-live-link/{id}','AdvertiserController@checkLiveLink')->name('order.check.live.link');
    Route::post('reason','AdvertiserController@reason')->name('reason');
    Route::get('profile','AdvertiserController@profile')->name('profile');
    Route::post('profile','AdvertiserController@profileUpdate')->name('profile.update');
    Route::get('site-filter','AdvertiserController@siteFilter')->name('site.filter');
    Route::get('order-update/{id}','AdvertiserController@orderUpdate')->name('order.update');
    Route::post('order-update','AdvertiserController@orderUpdates')->name('order.updates');

//    Favorite Sites
    Route::get('favorite','AdvertiserController@favorite')->name('favorite');
    Route::get('favorite-sites','AdvertiserController@favorite_sites')->name('sites.favorite');

    // Payments
    Route::GET( "wallet", "WalletController@index" )->name( "wallet.index" );
    Route::GET( "wallet/top-up", "WalletController@top_up_wallet" )->name( "wallet.top-up" );
    Route::PATCH( "wallet/update", "WalletController@update_wallet" )->name( "wallet.update" );
    Route::GET( "wallet/payment/success", "PaymentController@payment_success" )->name( "wallet.payment.success" );
    Route::GET( "wallet/payment/cancelled", "PaymentController@payment_cancelled" )->name( "wallet.payment.cancelled" );

    Route::post('requests-reject', 'AdvertiserController@requestsReject')->name('requests.reject');

    Route::post( 'send-message', 'MessageController@send_message' )->name( 'send_message' );
} );

// Admin
Route::group( [ "middleware" => [ "auth", "redirect_if_not_authenticated" ], "as" => "admin.", "prefix" => "admin", "namespace" => "Admin" ] , function () {

    Route::get('cache-clear','AdminController@cache_clear')->name('cache.clear');


    Route::get('/dashboard','AdminController@index')->name('dashboard');
    Route::get('check-site','AdminController@checkSite')->name('check.site');
//    language
    Route::get('language','AdminController@language')->name('language');
    Route::get('language-status/{id}','AdminController@languageStatus')->name('language.status');

//    Category
    Route::get('add-category','AdminController@addCategory')->name('add.category')->middleware( "can:categories.create" );
    Route::post('store-category','AdminController@storeCategory')->name('store.category')->middleware( "can:categories.create" );
    Route::get('category','AdminController@category')->name('category')->middleware( "can:categories.view" );
    Route::get('del-category/{id}','AdminController@delCategory')->name('delcategory')->middleware( "can:categories.delete" );
    Route::get('edit-category/{id}','AdminController@editCategory')->name('editcategory')->middleware( "can:categories.update" );
    Route::post('update-category/{id}','AdminController@updateCategory')->name('updatecategory')->middleware( "can:categories.update" );

    Route::get('get-user-sites/{id}','AdminController@getUserSites')->name('get.user.sites');

//    Website
    Route::get('site','AdminController@site')->name('site')->middleware( "can:sites.view" );
    Route::get('de-activate-site','AdminController@dsite')->name('dsite')->middleware( "can:sites.view" );
    Route::get('pending-activate-site','AdminController@psite')->name('psite')->middleware( "can:sites.view" );
    Route::get('change-status/{id}','AdminController@changeStatus')->name('change.status')->middleware( "can:sites.view" );
    Route::get('change-pending-status/{id}','AdminController@changePendingStatus')->name('change.pending.status')->middleware( "can:sites.view" );
    Route::get('add-site','AdminController@addSite')->name('add.Site')->middleware( "can:sites.create" );
    Route::post('store-site','AdminController@storeSite')->name('store.Site')->middleware( "can:sites.create" );
    Route::get('del-site/{id}','AdminController@delSite')->name('del.Site')->middleware( "can:sites.delete" );
    Route::get('edit-site/{id}','AdminController@editSite')->name('edit.Sites')->middleware( "can:sites.update" );
    Route::post('update-site/{id}','AdminController@updateSite')->name('update.Site')->middleware( "can:sites.update" );
    Route::get('reject-site/{id}','AdminController@rejectSite')->name('reject.Site')->middleware( "can:sites.delete" );
    Route::get('rejected-site','AdminController@rejectedSite')->name('rejected.Site')->middleware( "can:sites.delete" );

    // Roles
    Route::GET( "roles", "RoleController@index" )->name( "roles.index" )->middleware( "can:roles.view" );
    Route::GET( "roles/create", "RoleController@create" )->name( "roles.create" )->middleware( "can:roles.create" );
    Route::POST( "roles", "RoleController@store" )->name( "roles.store" )->middleware( "can:roles.create" );
    Route::GET( "roles/{role}/edit", "RoleController@edit" )->name( "roles.edit" )->middleware( "can:roles.update" );
    Route::PATCH( "roles/{role}", "RoleController@update" )->name( "roles.update" )->middleware( "can:roles.update" );
    Route::DELETE( "roles/{role}", "RoleController@delete" )->name( "roles.destroy" )->middleware( "can:roles.delete" );

    // Users
    Route::GET( "users", "UserController@index" )->name( "users.index" )->middleware( "can:users.view" );
    Route::GET( "users/create", "UserController@create" )->name( "users.create" )->middleware( "can:users.create" );
    Route::POST( "users", "UserController@store" )->name( "users.store" )->middleware( "can:users.create" );
    Route::GET( "users/{user}/edit", "UserController@edit" )->name( "users.edit" )->middleware( "can:users.update" );
    Route::PATCH( "users/{user}", "UserController@update" )->name( "users.update" )->middleware( "can:users.update" );
    Route::DELETE( "users/{user}", "UserController@delete" )->name( "users.destroy" )->middleware( "can:users.delete" );
    Route::GET( "user-status/{id}", "UserController@status" )->name( "user.status" )->middleware( "can:users.view" );

    // Staff
    Route::GET( "staff", "StaffController@index" )->name( "staff.index" )->middleware( "can:staff.view" );
    Route::GET( "staff/create", "StaffController@create" )->name( "staff.create" )->middleware( "can:staff.create" );
    Route::POST( "staff", "StaffController@store" )->name( "staff.store" )->middleware( "can:staff.create" );
    Route::GET( "staff/{id}/edit", "StaffController@edit" )->name( "staff.edit" )->middleware( "can:staff.update" );
    Route::PATCH( "staff/{id}", "StaffController@update" )->name( "staff.update" )->middleware( "can:staff.update" );
    Route::DELETE( "staff/{id}", "StaffController@delete" )->name( "staff.destroy" )->middleware( "can:staff.delete" );

    Route::GET( "task", "TaskController@index" )->name( "task.index" )->middleware( "can:task.view" );
    Route::GET( "task-detail/{id}", "TaskController@detail" )->name( "task.detail" )->middleware( "can:task.view" );
    Route::GET( "user-task-detail/{id}", "TaskController@userTaskDetail" )->name( "user.task.detail" )->middleware( "can:task.view" );
    Route::GET( "task-filter", "TaskController@filter" )->name( "task.filter" )->middleware( "can:task.view" );

    Route::get('profile','TaskController@profile')->name('profile');
    Route::post('profile','TaskController@profileUpdate')->name('profile.update');

    Route::post('profile','TaskController@profileUpdate')->name('profile.update');
    Route::get('site-filter','TaskController@siteFilter')->name('site.filter');

    // Wallet Top Up History
    Route::GET( "wallet/top-up/history", "WalletTopUpController@index" )->name( "wallet.top_up.history" );

    // Withdraw Request
    Route::GET( "wallet/withdraw/requests", "WalletController@withdraw_requests" )->name( "wallet.withdraw.request" ) ;
    Route::GET( "wallet/withdraw/requests-status/{id}", "WalletController@withdraw_requests_status" )->name( "wallet.withdraw.request.status" ) ;

    // Transaction History
    Route::GET( "wallet/transaction/history", "WalletController@index" )->name( "wallet.transaction.history" );
    Route::GET( "wallet/transactions", "WalletController@create_transaction" )->name( "wallet.transaction.create" );
    Route::POST( "wallet/transactions", "WalletController@store_transaction" )->name( "wallet.transaction.store" );

    // Blog
    Route::GET( "blog", "BlogController@blog" )->name( "blog" );
    Route::GET( "blog-create", "BlogController@create" )->name( "blog.create" );
    Route::POST( "blog-store", "BlogController@store" )->name( "blog.store" );
    Route::GET( "blog-delete/{id}", "BlogController@delete" )->name( "blog.delete" );
    Route::GET( "blog-edit/{id}", "BlogController@edit" )->name( "blog.edit" );

app/Http/Controllers/Admin/StaffController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Role;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class StaffController extends Controller
{
    public function index ()
    {
        $users = User::select( "id", "name", "email", "role_id", "created_at" )
            ->whereHas( "role", function ( $query ) {
                $query->whereNotIn( "roles.id", [ 1, 2, 3 ] );
            } )
            ->with( "role:id,role" )
            ->latest()
            ->get();

        return view( "admin.staff.index", compact( "users" ) );
    }

    public function create ()
    {
        $roles = Role::whereNotIn( "id", [ 1, 2, 3 ] )
            ->select( "id", "role" )
            ->latest()
            ->get();

        if ( count( $roles ) ) {
            return view( "admin.staff.create", compact( "roles" ) );

        } else {
            return redirect()->route( "admin.roles.index" )->with( "error", "To create staff member, create at least one role." );
        }
    }

    public function store ( Request $request )
    {
        $request->validate( [
            'role' => ['required', 'max:255'],
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:6', 'confirmed'],
        ] );

        if ( in_array( $request->role, [ 1, 2, 3 ] ) ) {
            return redirect()->back()->withInput()->with( "error", "Invalid role!" );
        }

        DB::beginTransaction();

        try {
            $user = new User();
            $user->name = $request->name;
            $user->email = $request->email;
            $user->role_id = $request->role;
            $user->password = Hash::make( $request->password );
            $user->save();

            DB::commit();

        } catch ( \Exception $e ) {
            DB::rollBack();

            return $e->getMessage();
        }

        return redirect()->route( "admin.staff.index" )->with( "success", "Staff member has been created." );
    }

    public function edit ( Request $request, $id )
    {
        if ( User::where( "id", $id )->doesntExist() ) {
            return redirect()->route( "admin.staff.index" );
        }

        $user = User::where( "id", $id )
            ->select( "id", "name", "email", "role_id" )
            ->latest()
            ->first();

        $roles = Role::whereNotIn( "id", [ 1, 2, 3 ] )
            ->select( "id", "role" )
            ->latest()
            ->get();

        return view( "admin.staff.edit", compact( "user", "roles" ) );
    }

    public function update ( Request $request, $id )
    {
        $request->validate( [
            'role' => ['required', 'max:255'],
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users,email,' . $id],
            'password' => ['nullable', 'string', 'min:6', 'confirmed'],
        ] );

        if ( in_array( $request->role, [ 1, 2, 3 ] ) ) {
            return redirect()->back()->withInput()->with( "error", "Invalid role!" );
        }

        if ( User::where( "id", $id )->exists() ) {
            $user = User::findOrFail( $id );

            DB::beginTransaction();

            try {
                $user->name = $request->name;
                $user->email = $request->email;
                $user->role_id = $request->role;

                if ( isset( $request->password ) && $request->password != "" ) {
                    $user->password = Hash::make( $request->password );
                }

                $user->save();

                DB::commit();

            } catch ( \Exception $e ) {
                DB::rollBack();

                return $e->getMessage();
            }
        }

        return redirect()->route( "admin.staff.index" )->with( "success", "Staff member has been updated." );
    }

    public function delete ( Request $request, $id )
    {
        if ( User::where( "id", $id )->exists() ) {
            User::where( "id", $id )->delete();
        }

        return redirect()->route( "admin.staff.index" )->with( "success", "Staff member has been deleted." );
    }
}

resources/views/admin/staff/create.blade.php
@extends('layout.admin.app')
@section('title')
    Add New Staff Member
@endsection

@section( "css" )

@endsection

@section('content')
    <div class="main-content {{ config('app_logo.BLOCKCOLOR') }}">
        <div class="page-content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                            <h4 class="mb-sm-0 font-size-18 {{ config('app_logo.TEXTCOLOR') }}">Add New Staff Member</h4>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="card {{ config('app_logo.BLOCKCOLOR') }} shadow-lg">
                            <div class="card-body">
                                <form action="{{ route('admin.staff.store') }}" method="POST" id="user_form">
                                    @csrf

                                    <div class="col-6">
                                        <div class="form-group mb-3">
                                            <label for="role">Role</label>

                                            <select id="role" name="role" class="form-control @error( 'role' ) is-invalid @enderror input_field">
                                                <option value="">Select Role</option>

                                                @foreach ( $roles as $role )
                                                    @php $role_status = ""; @endphp

                                                    @if ( old( "role" ) && old( "role" ) == $role->id )
                                                        @php $role_status = "selected"; @endphp
                                                    @endif

                                                    <option value="{{ $role->id }}" {{ $role_status }}>{{ $role->role }}</option>
                                                @endforeach
                                            </select>

                                            @error( 'role' )
                                                <small class="text-danger form-text">{{ $message }}</small>
                                            @enderror

                                            <small class="text-danger form-text input_field_validation_status" id="role_validation_status"></small>
                                        </div>

                                        <div class="form-group mb-3">
                                            <label for="name">Name</label>

                                            <input type="text" id="name" name="name" class="form-control @error( 'name' ) is-invalid @enderror input_field" placeholder="Name" value="{{ old( 'name' ) }}">

                                            @error( 'name' )
                                                <small class="text-danger form-text">{{ $message }}</small>
                                            @enderror

                                            <small class="text-danger form-text input_field_validation_status" id="name_validation_status"></small>
                                        </div>

                                        <div class="form-group mb-3">
                                            <label for="email">E-mail Address</label>

                                            <input type="text" id="email" name="email" class="form-control @error( 'email' ) is-invalid @enderror input_field" placeholder="E-mail Address" value="{{ old( 'email' ) }}">

                                            @error( 'email' )
                                                <small class="text-danger form-text">{{ $message }}</small>
                                            @enderror

                                            <small class="text-danger form-text input_field_validation_status" id="email_validation_status"></small>
                                        </div>

                                        <div class="form-group mb-3">
                                            <label for="password">Password</label>

                                            <input type="password" id="password" name="password" class="form-control @error( 'password' ) is-invalid @enderror input_field" placeholder="Password">

                                            @error( 'password' )
                                                <small class="text-danger form-text">{{ $message }}</small>
                                            @enderror

                                            <small class="text-danger form-text input_field_validation_status" id="password_validation_status"></small>
                                        </div>

                                        <div class="form-group mb-3">
                                            <label for="confirm_password">Confirm Password</label>

                                            <input type="password" id="confirm_password" name="password_confirmation" class="form-control @error( 'confirm_password' ) is-invalid @enderror input_field" placeholder="Confirm Password">

                                            @error( 'confirm_password' )
                                                <small class="text-danger form-text">{{ $message }}</small>
                                            @enderror

                                            <small class="text-danger form-text input_field_validation_status" id="confirm_password_validation_status"></small>
                                        </div>

                                        <div class="form-group mb-1">
                                            <button type="submit" id="submitBtn" class="btn btn-primary px-4">Submit</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <footer class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <script>document.write(new Date().getFullYear())</script> © Publication Media.
                    </div>
                    <div class="col-sm-6">
                        <div class="text-sm-end d-none d-sm-block">
{{--                            Design & Develop by Themesbrand--}}
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>
@endsection

@push('scripts')
    <script src="{{ asset( 'js/users/create.js' ) }}">
@endpush

resources/views/admin/staff/edit.blade.php
@extends('layout.admin.app')
@section('title')
    Edit Staff Member
@endsection

@section( "css" )

@endsection

@section('content')
    <div class="main-content {{ config('app_logo.BLOCKCOLOR') }}">
        <div class="page-content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                            <h4 class="mb-sm-0 font-size-18 {{ config('app_logo.TEXTCOLOR') }}">Edit Staff Member</h4>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="card {{ config('app_logo.BLOCKCOLOR') }} shadow-lg">
                            <div class="card-body">
                                <form action="{{ route('admin.staff.update', [ "id" => $user->id ]) }}" method="POST" id="user_form">
                                    @csrf
                                    @method( "PATCH" )

                                    <div class="col-6">
                                        <div class="form-group mb-3">
                                            <label for="role">Role</label>

                                            <select id="role" name="role" class="form-control @error( 'role' ) is-invalid @enderror input_field">
                                                @foreach ( $roles as $role )
                                                    @php
                                                        $role_status = "";

                                                        if ( $role->id == $user->role_id ) {
                                                            $role_status = "selected";
                                                        }
                                                    @endphp

                                                    <option value="{{ $role->id }}" {{ $role_status }}>{{ $role->role }}</option>
                                                @endforeach
                                            </select>

                                            @error( 'role' )
                                                <small class="text-danger form-text">{{ $message }}</small>
                                            @enderror

                                            <small class="text-danger form-text input_field_validation_status" id="role_validation_status"></small>
                                        </div>

                                        <div class="form-group mb-3">
                                            <label for="name">Name</label>

                                            <input type="text" id="name" name="name" class="form-control @error( 'name' ) is-invalid @enderror input_field" placeholder="Name" value="{{ $user->name }}">

                                            @error( 'name' )
                                                <small class="text-danger form-text">{{ $message }}</small>
                                            @enderror

                                            <small class="text-danger form-text input_field_validation_status" id="name_validation_status"></small>
                                        </div>

                                        <div class="form-group mb-3">
                                            <label for="email">E-mail Address</label>

                                            <input type="text" id="email" name="email" class="form-control @error( 'email' ) is-invalid @enderror input_field" placeholder="E-mail Address" value="{{ $user->email }}">

                                            @error( 'email' )
                                                <small class="text-danger form-text">{{ $message }}</small>
                                            @enderror

                                            <small class="text-danger form-text input_field_validation_status" id="email_validation_status"></small>
                                        </div>

                                        <div class="form-group mb-3">
                                            <label for="password">Password</label>

                                            <input type="password" id="password" name="password" class="form-control @error( 'password' ) is-invalid @enderror input_field" placeholder="Password">

                                            @error( 'password' )
                                                <small class="text-danger form-text">{{ $message }}</small>
                                            @enderror

                                            <small class="text-danger form-text input_field_validation_status" id="password_validation_status"></small>
                                        </div>

                                        <div class="form-group mb-3">
                                            <label for="confirm_password">Confirm Password</label>

                                            <input type="password" id="confirm_password" name="password_confirmation" class="form-control @error( 'confirm_password' ) is-invalid @enderror input_field" placeholder="Confirm Password">

                                            @error( 'confirm_password' )
                                                <small class="text-danger form-text">{{ $message }}</small>
                                            @enderror

                                            <small class="text-danger form-text input_field_validation_status" id="confirm_password_validation_status"></small>
                                        </div>

                                        <div class="form-group mb-1">
                                            <button type="submit" id="submitBtn" class="btn btn-primary px-4">Submit</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <footer class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <script>document.write(new Date().getFullYear())</script> © Publication Media.
                    </div>
                    <div class="col-sm-6">
                        <div class="text-sm-end d-none d-sm-block">
{{--                            Design & Develop by Themesbrand--}}
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>
@endsection

@push('scripts')
    <script src="{{ asset( 'js/users/update.js' ) }}">
@endpush