routes/web.php
Route::get('return-reserved-payment','CronController@return_reserved_payment')->name('return_reserved_payment');

ROUTE::GET( "/", "IndexController@index" )->name( '/' );
ROUTE::GET( "contact-us", "IndexController@contact" )->name( 'contact' );
ROUTE::GET( "privacy-policy", "IndexController@privacy_policy" )->name( 'privacy_policy' );
ROUTE::GET( "term-condition", "IndexController@term_condition" )->name( 'term_condition' );
ROUTE::GET( "blog/{slug}", "IndexController@blog_detail" )->name( 'blog_detail' );
ROUTE::GET( "blog", "IndexController@blog" )->name( 'blog' );
ROUTE::GET( "go_to_dashboard", "IndexController@go_to_dashboard" )->name( 'go_to_dashboard' );

Auth::routes();

// Publisher
Route::group( [ "middleware" => [ "auth", "redirect_if_not_authenticated" ], "as" => "publisher." ] , function () {
	// Dashboard
    Route::get('/dashboard','HomeController@dashboard')->name('dashboard');

    Route::group( [ "prefix" => "publisher" ], function () {

		// Sites
	    Route::get('list-site','HomeController@listSite')->name('list.site');
	    Route::get('disable-list-site','HomeController@dSite')->name('dsite');
	    Route::get('pending-list-site','HomeController@pSite')->name('psite');
	    Route::get('delete-site/{id}','HomeController@deleteSite')->name('del.site');
	    Route::get('add-new-site','HomeController@addSite')->name('add.site');
	    Route::post('post-site','HomeController@postSite')->name('post.site');
	    Route::get('edit-site/{id}','HomeController@editSite')->name('edit.site');
	    Route::post('update-site/{id}','HomeController@updateSite')->name('update.site');
        Route::get('site-members/{id}','HomeController@siteMember')->name('site.member');
        Route::get('download-file','HomeController@downloadFile')->name('download.file');
        Route::get('verify-owner-ship/{id}','HomeController@verifyOwnerShip')->name('verify.owner.ship');
        Route::get( 'publisher-activity-log', 'HomeController@activity_log' )->name('publisher.activity.log');
        Route::get('rejected-list-site','HomeController@rejectedSite')->name('rejected.site');

	    //Task
        Route::get('task','HomeController@task')->name('task');
        Route::get('show-task-detail/{id}','HomeController@showTaskDetail')->name('show.task.detail');
        Route::get('task-accept/{id}','HomeController@getTaskDetail')->name('task.accept');
        Route::get('task-reject/{id}','HomeController@getTaskReject')->name('task.reject');
        Route::post('request-approve','HomeController@requestApprove')->name('request.approve');
        Route::post('request-reject','HomeController@requestReject')->name('request.reject');

        Route::get('profile','HomeController@profile')->name('profile');
        Route::post('profile','HomeController@profileUpdate')->name('profile.update');

        // Wallet
        Route::GET( "wallet", "WalletController@index" )->name( "wallet.index" );
        Route::GET( "wallet/withdraw", "WalletController@withdraw" )->name( "wallet.withdraw" );
        Route::POST( "wallet/withdraw/request", "WalletController@withdraw_request" )->name( "wallet.withdraw.request" );

        Route::GET( "publisher-reserved", "WalletController@reserved" )->name( "wallet.reserved" );
        Route::post( 'send-message', 'MessageController@send_message' )->name( 'send_message' );
    } );
});

// Advertiser
Route::group( [ "middleware" => [ "auth", "redirect_if_not_authenticated" ], "as" => "advertiser.", "prefix" => "advertiser", "namespace" => "Advertiser" ] , function () {
    Route::get('get-user-sites/{id}','AdvertiserController@getUserSites')->name('get.user.sites');
    Route::get('dashboard','AdvertiserController@dashboardOrg')->name('dashboard.org');
    Route::get('sites','AdvertiserController@dashboard')->name('dashboard');
    Route::get('featured-sites','AdvertiserController@feature_dashboard')->name('feature_dashboard');
    Route::get('get-order/{id}','AdvertiserController@getOrder')->name('get.order');
    Route::post('get-order','AdvertiserController@getUserOrder')->name('get.user.order');

    //Activity Log
    Route::get( 'activity-log', 'AdvertiserController@activity_log' )->name('activity.log');

    Route::get('order-status','AdvertiserController@orderStatus')->name('order.status');
    Route::GET( "order-details/{id}","OrderController@order_details" )->name( "order.details" );
    Route::get('order-approve/{id}','AdvertiserController@orderApprove')->name('order.approve');
    Route::get('check-live-link/{id}','AdvertiserController@checkLiveLink')->name('order.check.live.link');
    Route::post('reason','AdvertiserController@reason')->name('reason');
    Route::get('profile','AdvertiserController@profile')->name('profile');
    Route::post('profile','AdvertiserController@profileUpdate')->name('profile.update');
    Route::get('site-filter','AdvertiserController@siteFilter')->name('site.filter');
    Route::get('order-update/{id}','AdvertiserController@orderUpdate')->name('order.update');
    Route::post('order-update','AdvertiserController@orderUpdates')->name('order.updates');

//    Favorite Sites
    Route::get('favorite','AdvertiserController@favorite')->name('favorite');
    Route::get('favorite-sites','AdvertiserController@favorite_sites')->name('sites.favorite');

    // Payments
    Route::GET( "wallet", "WalletController@index" )->name( "wallet.index" );
    Route::GET( "wallet/top-up", "WalletController@top_up_wallet" )->name( "wallet.top-up" );
    Route::PATCH( "wallet/update", "WalletController@update_wallet" )->name( "wallet.update" );
    Route::GET( "wallet/payment/success", "PaymentController@payment_success" )->name( "wallet.payment.success" );
    Route::GET( "wallet/payment/cancelled", "PaymentController@payment_cancelled" )->name( "wallet.payment.cancelled" );

    Route::post('requests-reject', 'AdvertiserController@requestsReject')->name('requests.reject');

    Route::post( 'send-message', 'MessageController@send_message' )->name( 'send_message' );
} );

// Admin
Route::group( [ "middleware" => [ "auth", "redirect_if_not_authenticated" ], "as" => "admin.", "prefix" => "admin", "namespace" => "Admin" ] , function () {

    Route::get('cache-clear','AdminController@cache_clear')->name('cache.clear');


    Route::get('/dashboard','AdminController@index')->name('dashboard');
    Route::get('check-site','AdminController@checkSite')->name('check.site');
//    language
    Route::get('language','AdminController@language')->name('language');
    Route::get('language-status/{id}','AdminController@languageStatus')->name('language.status');

//    Category
    Route::get('add-category','AdminController@addCategory')->name('add.category')->middleware( "can:categories.create" );
    Route::post('store-category','AdminController@storeCategory')->name('store.category')->middleware( "can:categories.create" );
    Route::get('category','AdminController@category')->name('category')->middleware( "can:categories.view" );
    Route::get('del-category/{id}','AdminController@delCategory')->name('delcategory')->middleware( "can:categories.delete" );
    Route::get('edit-category/{id}','AdminController@editCategory')->name('editcategory')->middleware( "can:categories.update" );
    Route::post('update-category/{id}','AdminController@updateCategory')->name('updatecategory')->middleware( "can:categories.update" );

    Route::get('get-user-sites/{id}','AdminController@getUserSites')->name('get.user.sites');

//    Website
    Route::get('site','AdminController@site')->name('site')->middleware( "can:sites.view" );
    Route::get('de-activate-site','AdminController@dsite')->name('dsite')->middleware( "can:sites.view" );
    Route::get('pending-activate-site','AdminController@psite')->name('psite')->middleware( "can:sites.view" );
    Route::get('change-status/{id}','AdminController@changeStatus')->name('change.status')->middleware( "can:sites.view" );
    Route::get('change-pending-status/{id}','AdminController@changePendingStatus')->name('change.pending.status')->middleware( "can:sites.view" );
    Route::get('add-site','AdminController@addSite')->name('add.Site')->middleware( "can:sites.create" );
    Route::post('store-site','AdminController@storeSite')->name('store.Site')->middleware( "can:sites.create" );
    Route::get('del-site/{id}','AdminController@delSite')->name('del.Site')->middleware( "can:sites.delete" );
    Route::get('edit-site/{id}','AdminController@editSite')->name('edit.Sites')->middleware( "can:sites.update" );
    Route::post('update-site/{id}','AdminController@updateSite')->name('update.Site')->middleware( "can:sites.update" );
    Route::get('reject-site/{id}','AdminController@rejectSite')->name('reject.Site')->middleware( "can:sites.delete" );
    Route::get('rejected-site','AdminController@rejectedSite')->name('rejected.Site')->middleware( "can:sites.delete" );

    // Roles
    Route::GET( "roles", "RoleController@index" )->name( "roles.index" )->middleware( "can:roles.view" );
    Route::GET( "roles/create", "RoleController@create" )->name( "roles.create" )->middleware( "can:roles.create" );
    Route::POST( "roles", "RoleController@store" )->name( "roles.store" )->middleware( "can:roles.create" );
    Route::GET( "roles/{role}/edit", "RoleController@edit" )->name( "roles.edit" )->middleware( "can:roles.update" );
    Route::PATCH( "roles/{role}", "RoleController@update" )->name( "roles.update" )->middleware( "can:roles.update" );
    Route::DELETE( "roles/{role}", "RoleController@delete" )->name( "roles.destroy" )->middleware( "can:roles.delete" );

    // Users
    Route::GET( "users", "UserController@index" )->name( "users.index" )->middleware( "can:users.view" );
    Route::GET( "users/create", "UserController@create" )->name( "users.create" )->middleware( "can:users.create" );
    Route::POST( "users", "UserController@store" )->name( "users.store" )->middleware( "can:users.create" );

app/Http/Controllers/Advertiser/MessageController.php
<?php

namespace App\Http\Controllers\Advertiser;

use App\Chat;
use App\Http\Controllers\Controller;
use App\Order;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class MessageController extends Controller
{
    public function send_message( Request $request ) {

        $this->validate( $request, [
            'message' => 'required',
            'order_id' => 'required',
            'to_id' => 'required',
        ] );

        $order_id = isset( $request->order_id ) ? $request->order_id : "";

        $chat = new Chat;
        $chat->to_id = isset( $request->to_id ) ? $request->to_id : 0;
        $chat->from_id = Auth::id();
        $chat->message = isset( $request->message ) ? $request->message : "";
        $chat->order_id = $order_id;
        $chat->save();

        $order = Order::where( 'order_id', $order_id )->first();

        if ( isset( $order->status ) && $order->status == 3 ) {
            Order::where( 'order_id', $order_id )->update( [
                'status' => 5,
            ] );
        }

//        return redirect()->back()->with( 'error', 'We have received your message and we will read it before sending it to the Buyer
        return redirect()->back()->with( 'error', 'SMS has been sent to the publisher successfully.' );
    }
}

app/Http/Controllers/Advertiser/OrderController.php
<?php

namespace App\Http\Controllers\advertiser;

use App\Chat;
use App\Http\Controllers\Controller;
use App\Order;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class OrderController extends Controller
{
    public function order_details ( $id )
    {
        $orderDetail = Order::where( 'order_id', $id )
            ->with( 'orderlinks' )
            ->with( 'site:id,user_id' )
            ->first();

        $from_id = Auth::id();

        $to_id = isset( $orderDetail->site->user_id ) ? $orderDetail->site->user_id : 0;

        $order_id = isset( $orderDetail->order_id ) ? $orderDetail->order_id : 0;

        $messages = Chat::select( "id", "from_id", "to_id", "message", "created_at" )
            ->where( function ( $query ) use ( $from_id, $to_id ) {
                $query->where(function ($query) use ($from_id, $to_id) {
                    $query->where("from_id", $from_id)
                        ->where("to_id", $to_id);
                });

                $query->orWhere(function ($query) use ($from_id, $to_id) {
                    $query->where("from_id", $to_id)
                        ->where("to_id", $from_id);
                });
            })
            ->where( 'order_id', $order_id )
            ->get();

        Chat::where( 'order_id', $order_id )->where( 'to_id', $from_id )->update([
            'is_read' => 1
        ]);

        if ( $orderDetail ) {
            return view( "advertiser.order.details", compact( "orderDetail", "messages" ) );
        }

        return redirect()->route( "advertiser.order.status" );
    }
}

app/Http/Controllers/Advertiser/PaymentController.php
<?php

namespace App\Http\Controllers\Advertiser;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use PayPal\Api\Item;
use PayPal\Api\Payer;
use PayPal\Api\Amount;
use PayPal\Api\Details;
use PayPal\Api\Payment;
use PayPal\Api\ItemList;
use PayPal\Api\WebProfile;
use PayPal\Api\InputFields;
use PayPal\Api\Transaction;
use PayPal\Api\RedirectUrls;
use PayPal\Api\PaymentExecution;

class PaymentController extends Controller
{
    public function create_payment ( Request $request )
    {
        $apiContext = new \PayPal\Rest\ApiContext(
            new \PayPal\Auth\OAuthTokenCredential(
                'AQ0ntySuxXLnnYJR7ssvDJ3GiDCw7oR6TKDSKYR2MW6hJecDhGid9deZ-BOBGDoCrB5i43YHsZhroLb3',     // ClientID
                'EC0E11seZp6JY6xf7IEGT6PbM_V9XbapX8a4cptAZ5cdCo3vvcVHqxCmUoAZ6_I_C3whaWQyyMuLe0sq'      // ClientSecret
            )
        );

        $payer = new Payer();
        $payer->setPaymentMethod("paypal");

        $amount = new Amount();
        $amount->setCurrency("USD")
            ->setTotal($request->amount);

        $transaction = new Transaction();
        $transaction->setAmount($amount)
            ->setDescription("Wallet top-up amount on Link Planet")
            ->setInvoiceNumber(uniqid());

        $redirectUrls = new RedirectUrls();
        $redirectUrls->setReturnUrl("https://linkplanet.co/public/")
            ->setCancelUrl("https://linkplanet.co/public/");

        // Add NO SHIPPING OPTION
        $inputFields = new InputFields();
        $inputFields->setNoShipping(1);

        $webProfile = new WebProfile();
        $webProfile->setName('Link Planet' . uniqid())->setInputFields($inputFields);

        $webProfileId = $webProfile->create($apiContext)->getId();

        $payment = new Payment();
        $payment->setExperienceProfileId($webProfileId); // no shipping
        $payment->setIntent("sale")
            ->setPayer($payer)
            ->setRedirectUrls($redirectUrls)
            ->setTransactions(array($transaction));

        try {
            $payment->create($apiContext);
        } catch (Exception $ex) {
            echo $ex;
            exit(1);
        }

        return $payment;
    }

    public function execute_payment ( Request $request )
    {
        $apiContext = new \PayPal\Rest\ApiContext(
            new \PayPal\Auth\OAuthTokenCredential(
                'AQ0ntySuxXLnnYJR7ssvDJ3GiDCw7oR6TKDSKYR2MW6hJecDhGid9deZ-BOBGDoCrB5i43YHsZhroLb3',     // ClientID
                'EC0E11seZp6JY6xf7IEGT6PbM_V9XbapX8a4cptAZ5cdCo3vvcVHqxCmUoAZ6_I_C3whaWQyyMuLe0sq'      // ClientSecret
            )
        );

        $paymentId = $request->paymentID;
        $payment = Payment::get($paymentId, $apiContext);

        $execution = new PaymentExecution();
        $execution->setPayerId($request->payerID);

        try {
            $result = $payment->execute($execution, $apiContext);
        } catch (Exception $ex) {
            echo $ex;
            exit(1);
        }

        return $result;
    }

    public function payment_success ()
    {
        return "Payment Success.";
    }

    public function payment_cancelled ()
    {
        return "Payment Cancelled.";
    }
}

resources/views/layout/advertiser/app.blade.php
@include('layout.advertiser.header')
@include('layout.advertiser.sidebar')

    @yield('content')

@include('layout.advertiser.footer')

resources/views/layout/advertiser/footer.blade.php
<!-- JAVASCRIPT -->
<script src="{{ asset('assets/libs/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('assets/libs/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('assets/libs/metismenu/metisMenu.min.js') }}"></script>
<script src="{{ asset('assets/libs/simplebar/simplebar.min.js') }}"></script>
<script src="{{ asset('assets/libs/node-waves/waves.min.js') }}"></script>

<!-- dashboard init -->
{{--<script src="{{ asset('assets/js/pages/dashboard.init.js') }}"></script>--}}

<!-- App js -->
<script src="{{ asset('assets/js/app.js') }}"></script>
<script src="{{ asset('js/header/header.js') }}"></script>
<script src="{{ asset( 'js/datatables/datatables.min.js' ) }}"></script>
@stack('scripts')
</body>
</html>

resources/views/layout/advertiser/header.blade.php
<!DOCTYPE html>
<html lang="en">
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>

    <meta charset="utf-8" />
    <title>@yield('title')</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="" name="description" />
    <meta content="" name="author" />
    <!-- App favicon -->
    <link rel="icon" type="image/x-icon" href="{{ asset( 'assets/images/favicon.png' ) }}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kantumruy+Pro:ital,wght@0,100..700;1,100..700&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

    <!-- Bootstrap Css -->
    <link href="{{ asset('assets/css/bootstrap-dark.min.css') }}" id="bootstrap-style" rel="stylesheet" type="text/css" />
    <!-- Icons Css -->
    <link href="{{ asset('assets/css/icons.min.css') }}" rel="stylesheet" type="text/css" />
    <!-- App Css-->
    <link href="{{ asset('assets/css/app-dark.min.css') }}" id="app-style" rel="stylesheet" type="text/css" />

    <link rel="stylesheet" href="{{ asset( 'css/datatables/datatables.min.css' ) }}">

    <style>
        .main_logo {
            max-width: 75%;
            height: auto;
        }

        .badge-counter {
            position: absolute;
            top: 0;
            right: 0;
            transform: translate(50%, -50%);
            background-color: #d6dc35; /* Bootstrap danger color */
            color: white;
            border-radius: 50%;
            padding: 0.25em 0.5em;
            font-size: 0.75em;
            font-weight: bold;
        }

        /*.table td, .table th {*/
        /*    text-align: center; !* Center align all <td> and <th> elements *!*/
        /*}*/
    </style>

    <style>
        .badge-counter {
            position: absolute;
            top: 0;
            right: 0;
            transform: translate(50%, -50%);
            background-color: #d6dc35; /* Bootstrap danger color */
            color: white;
            border-radius: 50%;
            padding: 0.25em 0.5em;
            font-size: 0.75em;
            font-weight: bold;
        }
    </style>

    @stack('css')
</head>

<body data-sidebar="dark" >
<!-- Begin page -->
<div id="layout-wrapper">

    <header id="page-topbar">
        <div class="navbar-header">
            <div class="d-flex">
                <!-- LOGO -->
                <div class="navbar-brand-box">
                    <a href="javascript:void(0)" class="logo logo-dark">
                    <span class="logo-sm">
                        <img src="{{ asset('assets/images/link-planet-logo.png') }}" alt="" height="22">
                    </span>
                        <span class="logo-lg">
                        <img src="{{ asset('assets/images/link-planet-logo.png') }}" alt="" class="main_logo">
                    </span>
                    </a>

                    <a href="javascript:void(0)" class="logo logo-light">
                    <span class="logo-sm">
                        <img src="{{ asset('assets/images/link-planet-logo.png') }}" alt="" height="22">
                    </span>
                        <span class="logo-lg">
                        <img src="{{ asset('assets/images/link-planet-logo.png') }}" alt="" class="main_logo">
                    </span>
                    </a>
                </div>

                <button type="button" class="btn btn-sm px-3 font-size-16 header-item waves-effect" id="vertical-menu-btn">
                    <i class="fa fa-fw fa-bars"></i>
                </button>
            </div>

            <div class="d-flex">
                <div class="dropdown d-inline-block">
                    <a href="{{ route('advertiser.wallet.index') }}"><span class="d-none d-xl-inline-block ms-1 badge badge-success bg-danger" style="font-size: 16px;" key="t-henry"><i class="bx bx-wallet "></i>  ${{ Auth::user()->wallet }}</span></a>

                    <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="d-none d-xl-inline-block ms-1 badge badge-success bg-primary" style="font-size: 16px;" key="t-henry">
                            <i class="fa fa-bell"></i>
                            <?php
                                $msg_count = count( unread_msg() );
                            ?>
                            <span class="badge-counter badge-warning">{{ isset( $msg_count ) && $msg_count <= 5 ? $msg_count : '5+' }}</span>
                        </span>

                    </button>
                    <div class="dropdown-menu dropdown-menu-end">
                        <!-- item-->
                        <div class="card-header">
                            Messages
                        </div>
                        @foreach( unread_msg() as $row )
                            <div class="card">
                                <a class="dropdown-item" href="{{ route( 'advertiser.order.details', $row->order_id ) }}">
                                    <div style="display: flex; flex-direction: row">
                                        <i class="bx bxs-bell-ring font-size-16 align-middle me-1"></i>
                                        <h5>{{ isset( $row->sender->name ) ? $row->sender->name : "" }}</h5>
                                    </div>
                                    <p class="jumbotron">{{ isset( $row->message ) ? substr( $row->message, 0, 40 ) : "" }} ... </p>
                                    <span class="notification-time"><span class="mr-1" role="img" aria-label="Emoji">💬</span>{{ isset( $row->created_at ) ? $row->created_at->diffForHumans() : "" }}</span>
                                </a>
                            </div>
                        @endforeach
                    </div>

                    <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
{{--                        <img class="rounded-circle header-profile-user" src="{{ url(env('APP_PROFILE_PATH')) }}" alt="Header Avatar">--}}

                        <span class="d-none d-xl-inline-block ms-1" key="t-henry">{{ Auth::user()->name }}</span>
                        <i class="mdi mdi-chevron-down d-none d-xl-inline-block"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-end">
                        <!-- item-->
                        <a class="dropdown-item" href="{{ route('advertiser.profile') }}"><i class="bx bx-user font-size-16 align-middle me-1"></i> <span key="t-profile">Profile</span></a>
                        <a class="dropdown-item" href="{{ route( 'advertiser.wallet.index' ) }}"><i class="bx bx-wallet font-size-16 align-middle me-1"></i> <span key="t-my-wallet">My Wallet</span></a>
{{--                        <a class="dropdown-item d-block" href="#"><span class="badge bg-success float-end">11</span><i class="bx bx-wrench font-size-16 align-middle me-1"></i> <span key="t-settings">Settings</span></a>--}}
{{--                        <a class="dropdown-item" href="auth-lock-screen.html"><i class="bx bx-lock-open font-size-16 align-middle me-1"></i> <span key="t-lock-screen">Lock screen</span></a>--}}
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item text-danger" href="javascript:void(0)" id="logout_link"><i class="bx bx-power-off font-size-16 align-middle me-1 text-danger"></i> <span key="t-logout">Logout</span></a>
                    </div>
                </div>
            </div>
        </div>

        <form method="POST" action="{{ route( 'logout' ) }}" id="logout_form">
            @csrf
        </form>
    </header>

resources/views/layout/advertiser/sidebar.blade.php
<!-- ========== Left Sidebar Start ========== -->
<div class="vertical-menu">

    <div data-simplebar class="h-100">

        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <!-- Left Menu Start -->
            <ul class="metismenu list-unstyled" id="side-menu">
                <li class="menu-title" key="t-menu">Menu</li>

                <li>
                    <a href="{{ route('advertiser.dashboard.org') }}" class="waves-effect">
                        <i class="bx bx-home-circle"></i>
{{--                                                <span class="badge rounded-pill bg-info float-end">04</span>--}}
                        <span key="t-dashboards">Dashboard</span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('advertiser.dashboard') }}" class="waves-effect">
                        <i class="bx bx-link-alt"></i>
                        <span key="t-dashboards">Sites</span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('advertiser.feature_dashboard') }}" class="waves-effect">
                        <i class="bx bx-link-alt"></i>
                        <span key="t-dashboards">Featured Sites</span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('advertiser.sites.favorite') }}" class="waves-effect">
                        <i class="bx bx-star"></i>
                        <span key="t-dashboards">Favorite Sites</span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('advertiser.order.status') }}" class="waves-effect">
                        <i class="bx bx-grid"></i>
                        <span key="t-dashboards">Task</span>
                    </a>
                </li>

                <li>
                    <a href="{{ route( 'advertiser.wallet.index' ) }}" class="waves-effect">
                        <i class="bx bx-wallet font-size-16 align-middle me-1"></i>
                        <span key="t-dashboards">My Wallet</span>
                    </a>
                </li>

                <li>
                    <a href="{{ route( 'advertiser.activity.log' ) }}" class="waves-effect">
                        <i class="bx bxs-timer font-size-16 align-middle me-1"></i>
                        <span key="t-activity-log">Activity Log</span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('advertiser.profile') }}" class="waves-effect">
                        <i class="bx bx-user-circle"></i>
                        <span key="t-dashboards">Profile</span>
                    </a>
                </li>
            </ul>
        </div>
        <!-- Sidebar -->
    </div>
</div>
<!-- Left Sidebar End -->